theme: jekyll-theme-dinky
remote_theme: pages-themes/dinky@v0.2.0
plugins:
- jekyll-remote-theme

title: Anita Taucher
description: _Data Scientist_ Especially Strong in Python and SQL

show_downloads: false
# google_analytics: [Your Google Analytics tracking ID]

markdown: kramdown
